<?php

namespace Frisky\AddressBookBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GroupOfUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupOfUsersRepository extends EntityRepository
{
}
